#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 17 16:36:12 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -cc_db Test_coverage -cc_dir /ihp/departments/D-SYA/work/miglioranza -cc_type c -L xil_defaultlib -L secureip --snapshot Symbol_mapper_tb_behav xil_defaultlib.Symbol_mapper_tb -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -cc_db Test_coverage -cc_dir /ihp/departments/D-SYA/work/miglioranza -cc_type c -L xil_defaultlib -L secureip --snapshot Symbol_mapper_tb_behav xil_defaultlib.Symbol_mapper_tb -log elaborate.log

