#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Nov 08 11:56:24 CET 2024
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: compile.sh
#
# ****************************************************************************
# delete log files (if exist)
reset_log()
{
logs=(compile.log xmvhdl.log xmvlog.log xmsc.log .tmp_log)
for (( i=0; i<${#logs[*]}; i++ )); do
  file="${logs[i]}"
  if [[ -e $file ]]; then
    rm -rf $file
  fi
done
}
reset_log
set -Eeuo pipefail

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# directory path for design sources and include directories (if any) wrt this path
origin_dir="."

# set xmvhdl command line args
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# compile design source files
$bin_path/xmvhdl -V93 $xmvhdl_opts -work xil_defaultlib  \
"$origin_dir/../../../../Pre-distorsion_filter.srcs/sources_1/new/Parallel_FIR_filter.vhd" \
"$origin_dir/../../../../Pre-distorsion_filter.srcs/sim_1/new/Parallel_FIR_filter_TB.vhd" \
2>&1 | tee compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null
