#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Sep 23 14:36:02 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -cc_db cov-report -cc_dir cov_test -cc_libs -cc_type s -L xil_defaultlib -L secureip --snapshot Parallel_FIR_filter_TB_func_impl xil_defaultlib.Parallel_FIR_filter_TB -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -cc_db cov-report -cc_dir cov_test -cc_libs -cc_type s -L xil_defaultlib -L secureip --snapshot Parallel_FIR_filter_TB_func_impl xil_defaultlib.Parallel_FIR_filter_TB -log elaborate.log

