# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/miglioranza/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_Control_unit_top_0_0/Design_2_Control_unit_top_0_0.xci
# IP: The module: 'Design_2_Control_unit_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_Control_unit_top_0_0/constrs_1/new/CU_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_Control_unit_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_Control_unit_top_0_0/Design_2_Control_unit_top_0_0.xci
# IP: The module: 'Design_2_Control_unit_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_Control_unit_top_0_0/constrs_1/new/CU_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_Control_unit_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
