#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 26 17:32:17 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim LDPC_encoder_tb_time_synth -key {Post-Synthesis:sim_1:Timing:LDPC_encoder_tb} -tclbatch LDPC_encoder_tb.tcl -log simulate.log -maxdeltaid 200000"
xsim LDPC_encoder_tb_time_synth -key {Post-Synthesis:sim_1:Timing:LDPC_encoder_tb} -tclbatch LDPC_encoder_tb.tcl -log simulate.log -maxdeltaid 200000

