# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/miglioranza/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/Design_2_LDPC_encoder_0_2.xci
# IP: The module: 'Design_2_LDPC_encoder_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_1 || ORIG_REF_NAME==axis_data_fifo_1} -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/sources_1/ip/sd_fec_0/sd_fec_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sd_fec_0 || ORIG_REF_NAME==sd_fec_0} -quiet] -quiet

# XDC: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/constrs_1/new/Encoder_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_LDPC_encoder_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/Design_2_LDPC_encoder_0_2.xci
# IP: The module: 'Design_2_LDPC_encoder_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_1 || ORIG_REF_NAME==axis_data_fifo_1} -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/sources_1/ip/sd_fec_0/sd_fec_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sd_fec_0 || ORIG_REF_NAME==sd_fec_0} -quiet] -quiet

# XDC: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_LDPC_encoder_0_2/constrs_1/new/Encoder_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_LDPC_encoder_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
