#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 17 10:44:34 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4bb835d4c9174b4ca825b7079037e5bb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Parallel_FIR_filter_TB_behav xil_defaultlib.Parallel_FIR_filter_TB -log elaborate.log"
xelab -wto 4bb835d4c9174b4ca825b7079037e5bb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Parallel_FIR_filter_TB_behav xil_defaultlib.Parallel_FIR_filter_TB -log elaborate.log

