#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Sep 23 11:49:43 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Parallel_FIR_filter_TB_behav -key {Behavioral:sim_1:Functional:Parallel_FIR_filter_TB} -tclbatch Parallel_FIR_filter_TB.tcl -view /home/miglioranza/Pre-distorsion_filter/Parallel_FIR_filter_TB_behav.wcfg -view /home/miglioranza/Pre-distorsion_filter/Parallel_FIR_filter_TB_post_synt.wcfg -log simulate.log"
xsim Parallel_FIR_filter_TB_behav -key {Behavioral:sim_1:Functional:Parallel_FIR_filter_TB} -tclbatch Parallel_FIR_filter_TB.tcl -view /home/miglioranza/Pre-distorsion_filter/Parallel_FIR_filter_TB_behav.wcfg -view /home/miglioranza/Pre-distorsion_filter/Parallel_FIR_filter_TB_post_synt.wcfg -log simulate.log

