#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jul 26 16:05:59 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/22.03/tools.lnx86/inca/bin/64bit"

# set xmelab command line args
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set design libraries
design_libs_elab="-libname xil_defaultlib -libname secureip"

# run elaboration
$bin_path/xmelab $xmelab_opts $design_libs_elab xil_defaultlib.Scrambler_32bits_TB
