#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jul 26 16:06:00 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/22.03/tools.lnx86/inca/bin/64bit"

# set xmsim command line args
xmsim_opts="-64bit -logfile simulate.log -gui"

# run simulation
$bin_path/xmsim $xmsim_opts xil_defaultlib.Scrambler_32bits_TB -input Scrambler_32bits_TB_simulate.do
