# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/miglioranza/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_Polyphase_filter_0_0/Design_2_Polyphase_filter_0_0.xci
# IP: The module: 'Design_2_Polyphase_filter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_Polyphase_filter_0_0/Polyphase_Filter_FI.srcs/sources_1/ip/axis_data_fifo_poly_filter/axis_data_fifo_poly_filter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_poly_filter || ORIG_REF_NAME==axis_data_fifo_poly_filter} -quiet] -quiet

# XDC: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_Polyphase_filter_0_0/Polyphase_Filter_FI.srcs/constrs_1/new/Polyphase_filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_Polyphase_filter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/miglioranza/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_Polyphase_filter_0_0/Design_2_Polyphase_filter_0_0.xci
# IP: The module: 'Design_2_Polyphase_filter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_Polyphase_filter_0_0/Polyphase_Filter_FI.srcs/sources_1/ip/axis_data_fifo_poly_filter/axis_data_fifo_poly_filter.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_poly_filter || ORIG_REF_NAME==axis_data_fifo_poly_filter} -quiet] -quiet

# XDC: /home/miglioranza/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_Polyphase_filter_0_0/Polyphase_Filter_FI.srcs/constrs_1/new/Polyphase_filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_Polyphase_filter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
