#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Apr 18 13:13:41 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# set xmelab command line args
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log -FAULT_WORK fault_db2"

# set design libraries
design_libs_elab="-libname xil_defaultlib -libname secureip"

# set fault injection parameters
fi_opts="-fault_dbg -fault_top mapper_tb  -fault_overwrite -fault_file ./fault_list_SET"


# run elaboration
$bin_path/xmelab $xmelab_opts $fi_opts $design_libs_elab xil_defaultlib.mapper_tb
