#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Apr 18 13:13:42 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# === Range of Fault IDs to Inject ===
#!/bin/bash
 

# === Installation path for xmsim ===
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# === Simulation options (logfile removed to avoid parallel conflicts) ===
xmsim_opts="-64bit"

# === Number of parallel jobs (adjust to match your system's cores) ===
NUM_JOBS=40

# === Fault IDs to inject ===
fault_ids=(
404
634
645
656
667
678
689
700
784
795
806
817
828
839
850
861
872
956
967
978
989
1000
1011
1022
1033
1044
1055
1066
1077
1088
1099
1183
1477
1488
1499
1510
1521
1532
1750
1783
1803
2098
2109
2120
2277
2288
2299
2310
2321
2332
2343
2360
2395
2479
2490
2515
2622
2633
2644
2655
2666
2677
2688
2699
2948
3105
3116
3127
3138
3149
3160
3171
3328
3339
3350
3361
3372
3383
3394
3405
3416
3573
3584
3595
3606
3617
3628
3639
3650
3661
3672
3683
3694
3705
3716
3873

)

# === Function to run a simulation ===
run_simulation() {
    local fault_id=$1
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting Fault ID: $fault_id"

    local fi_opts="-fault_sim_run -fault_checker_on -fault_timeout 1000ns -fault_tw 50ns:450ns -fault_id $fault_id -fault_work fault_db"

    $bin_path/xmsim $xmsim_opts $fi_opts xil_defaultlib.mapper_tb -input mapper_tb_simulate.do > /dev/null 2>&1
    local exit_status=$?
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Finished Fault ID: $fault_id (Exit: $exit_status)"
    return $exit_status
}

# === Export for xargs parallelization ===
export -f run_simulation
export bin_path xmsim_opts

# === Run in parallel ===
printf "%s\n" "${fault_ids[@]}" | xargs -n 1 -P $NUM_JOBS -I {} bash -c 'run_simulation "$@"' _ {}

# === Final report ===
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running xfr..."
$bin_path/xfr -fault_work ./fault_db -logfile fault_report_SEU.log 2>&1 | tee xfr_debug.log
exit_status=$?
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Fault report generated (Exit: $exit_status)"
