#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Apr 18 13:13:42 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# === Ranges of Fault IDs to Inject ===
#!/bin/bash

# === Path to xfr binary ===
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# === Run xfr to generate fault report ===
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running xfr..."
$bin_path/xfr -fault_work ./fault_db -logfile fault_report_SEU.log 2>&1 | tee xfr_debug.log
exit_status=$?
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Fault report generated (Exit: $exit_status)"

exit $exit_status
