#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Apr 18 13:13:42 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# === Ranges of Fault IDs to Inject ===
RANGES=(
       "8 13"
    "3197 3687"
)

# Installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# xmsim command line args (removed global logfile to avoid conflicts)
xmsim_opts="-64bit"

# Number of parallel jobs (adjust based on CPU cores)
NUM_JOBS=75  # Optimized for 32-core machine

# Function to run a single simulation (no log files)
run_simulation() {
    local fault_id=$1

    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting Fault ID: $fault_id"

    # Normal fault injection for all IDs
    local fi_opts="-fault_sim_run -fault_checker_on -fault_timeout 1000ns -fault_tw 50ns:450ns -fault_id $fault_id -fault_work fault_db2"

    $bin_path/xmsim $xmsim_opts $fi_opts xil_defaultlib.mapper_tb -input mapper_tb_simulate.do > /dev/null 2>&1

    exit_status=$?
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Finished Fault ID: $fault_id (Exit status: $exit_status)"
    return $exit_status
}

# Export function and variables for parallel execution
export -f run_simulation
export bin_path xmsim_opts

# Generate all fault IDs from the specified ranges
fault_ids=()
for range in "${RANGES[@]}"; do
    read start end <<< "$range"
    fault_ids+=($(seq $start $end))
done

# Run simulations in parallel using xargs
printf "%s\n" "${fault_ids[@]}" | xargs -n 1 -P $NUM_JOBS -I {} bash -c 'run_simulation {}'

echo "All simulations completed."

# Run xfr report only after all simulations are done
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Generating fault report..."
$bin_path/xfr -fault_work ./fault_db2 -logfile fault_report_SET.log
exit_status=$?
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Fault report generated (Exit status: $exit_status)"
