# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/miglioranza/FEC/FEC.srcs/sources_1/ip/sd_fec_0/sd_fec_0.xci
# IP: The module: 'sd_fec_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miglioranza/FEC/FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fec_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/miglioranza/FEC/FEC.srcs/sources_1/ip/sd_fec_0/sd_fec_0.xci
# IP: The module: 'sd_fec_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miglioranza/FEC/FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fec_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
