#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Oct 28 13:32:11 CET 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -cc_db Encoder_code_coverage -cc_dir Encoder.sim -cc_type sbc -L xil_defaultlib -L unisims_ver -L secureip --snapshot LDPC_encoder_tb_func_synth xil_defaultlib.LDPC_encoder_tb xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -cc_db Encoder_code_coverage -cc_dir Encoder.sim -cc_type sbc -L xil_defaultlib -L unisims_ver -L secureip --snapshot LDPC_encoder_tb_func_synth xil_defaultlib.LDPC_encoder_tb xil_defaultlib.glbl -log elaborate.log

