#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 21 11:37:22 CEST 2024
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Scrambler_32bits_TB_behav -key {Behavioral:sim_1:Functional:Scrambler_32bits_TB} -tclbatch Scrambler_32bits_TB.tcl -log simulate.log"
xsim Scrambler_32bits_TB_behav -key {Behavioral:sim_1:Functional:Scrambler_32bits_TB} -tclbatch Scrambler_32bits_TB.tcl -log simulate.log

