set_property SRC_FILE_INFO {cfile:/home/miglioranza/FEC/FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc rfile:../../../../../FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc id:1 order:EARLY scoped_inst:LDPC_encoder_1x16_inst0/ldpc_encoder} [current_design]
set_property SRC_FILE_INFO {cfile:/home/miglioranza/FEC/FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc rfile:../../../../../FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc id:2 order:EARLY scoped_inst:LDPC_encoder_1x16_inst1/ldpc_encoder} [current_design]
set_property SRC_FILE_INFO {cfile:/home/miglioranza/FEC/FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc rfile:../../../../../FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc id:3 order:EARLY scoped_inst:LDPC_encoder_1x16_inst2/ldpc_encoder} [current_design]
set_property SRC_FILE_INFO {cfile:/home/miglioranza/FEC/FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc rfile:../../../../../FEC.gen/sources_1/ip/sd_fec_0/sd_fec_0/sd_fec_0_in_context.xdc id:4 order:EARLY scoped_inst:LDPC_encoder_1x16_inst3/ldpc_encoder} [current_design]
set_property SRC_FILE_INFO {cfile:/home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_in_context.xdc rfile:../../../../../FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_in_context.xdc id:5 order:EARLY scoped_inst:input_fifo/axis_fifo} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1.502 [get_pins LDPC_encoder_1x16_inst0/ldpc_encoder/core_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst0/ldpc_encoder/m_axis_dout_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst0/ldpc_encoder/m_axis_status_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst0/ldpc_encoder/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst0/ldpc_encoder/s_axis_ctrl_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst0/ldpc_encoder/s_axis_din_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells LDPC_encoder_1x16_inst0/ldpc_encoder]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1.502 [get_pins LDPC_encoder_1x16_inst1/ldpc_encoder/core_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst1/ldpc_encoder/m_axis_dout_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst1/ldpc_encoder/m_axis_status_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst1/ldpc_encoder/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst1/ldpc_encoder/s_axis_ctrl_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst1/ldpc_encoder/s_axis_din_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells LDPC_encoder_1x16_inst1/ldpc_encoder]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1.502 [get_pins LDPC_encoder_1x16_inst2/ldpc_encoder/core_clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst2/ldpc_encoder/m_axis_dout_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst2/ldpc_encoder/m_axis_status_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst2/ldpc_encoder/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst2/ldpc_encoder/s_axis_ctrl_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst2/ldpc_encoder/s_axis_din_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells LDPC_encoder_1x16_inst2/ldpc_encoder]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1.502 [get_pins LDPC_encoder_1x16_inst3/ldpc_encoder/core_clk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst3/ldpc_encoder/m_axis_dout_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst3/ldpc_encoder/m_axis_status_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst3/ldpc_encoder/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst3/ldpc_encoder/s_axis_ctrl_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins LDPC_encoder_1x16_inst3/ldpc_encoder/s_axis_din_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells LDPC_encoder_1x16_inst3/ldpc_encoder]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins input_fifo/axis_fifo/s_aclk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells input_fifo/axis_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells LDPC_encoder_1x16_inst0/ldpc_encoder]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells LDPC_encoder_1x16_inst1/ldpc_encoder]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells LDPC_encoder_1x16_inst2/ldpc_encoder]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells LDPC_encoder_1x16_inst3/ldpc_encoder]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells input_fifo/axis_fifo]
