webtalk_init -webtalk_dir /home/miglioranza/Pre-distorsion_filter/Pre-distorsion_filter.sim/sim_1/behav/xsim/xsim.dir/Parallel_FIR_filter_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 17 15:12:33 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212366726_209153169_210770516_402" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3bd1a919-b5a9-47f1-b1ca-b196ced9efa7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4bb835d4c9174b4ca825b7079037e5bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "161" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseServer" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Server release 7.9 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-4627 v2 @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1199.835 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "135.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "140 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "135064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 68510974 -regid "212366726_209153169_210770516_402" -xml /home/miglioranza/Pre-distorsion_filter/Pre-distorsion_filter.sim/sim_1/behav/xsim/xsim.dir/Parallel_FIR_filter_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/miglioranza/Pre-distorsion_filter/Pre-distorsion_filter.sim/sim_1/behav/xsim/xsim.dir/Parallel_FIR_filter_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/miglioranza/Pre-distorsion_filter/Pre-distorsion_filter.sim/sim_1/behav/xsim/xsim.dir/Parallel_FIR_filter_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
