#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 29 13:26:38 CET 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -cc_db Interleaver_CC -cc_libs -cc_type sbc -L xil_defaultlib -L secureip --snapshot tb_block_interleaver_func_synth xil_defaultlib.tb_block_interleaver -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -cc_db Interleaver_CC -cc_libs -cc_type sbc -L xil_defaultlib -L secureip --snapshot tb_block_interleaver_func_synth xil_defaultlib.tb_block_interleaver -log elaborate.log

