# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/sd_fec_0/sd_fec_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sd_fec_0 || ORIG_REF_NAME==sd_fec_0} -quiet] -quiet
