#!/bin/bash -f

# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 16 14:15:46 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# set xmsim command line args
xmsim_opts="-64bit"

# === Number of parallel jobs (adjust to match your system's cores) ===
NUM_JOBS=20

# === Fault IDs to inject ===
fault_ids=(
349
450
457
461
468
474
480
483
490
495
502
508
514
521
528
534
540
547
551
558
565
572
578
585
592
598
605
612
616
623
630
636
639
646
653
658
695
710
725
740
755
770
785
800
815
830
845
860
875
882
889
896
903
910
917
923
929
935
941
947
954
961
968
975
982
988
991
998
1005
1012
1019
1026
1033
1039
1042
1079
1083
1098
1124
1139
1154
1169
1173
1188
1203
1207
1222
1226
1241
1245
1260
 
)

# === Function to run a simulation ===
run_simulation(){

local fault_id=$1
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting Fault ID: $fault_id"
local fi_opts="-fault_sim_run  -fault_tw 20ns:940ns -fault_id $fault_id -fault_work fault_db"

$bin_path/xmsim $xmsim_opts $fi_opts xil_defaultlib.Symbol_mapper_tb -input Symbol_mapper_tb_simulate.do > /dev/null 2>&1
local exit_status=$?
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Finished Fault ID: $fault_id (Exit: $exit_status)"
return $exit_status
} 


# === Export for xargs parallelization ===
export -f run_simulation
export bin_path xmsim_opts

# === Run in parallel ===
printf "%s\n" "${fault_ids[@]}" | xargs -n 1 -P $NUM_JOBS -I {} bash -c 'run_simulation "$@"' _ {}

