#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 16 14:15:46 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# set xmsim command line args
xmsim_opts="-64bit -logfile simulate.log "

# set fault injection parameters
fi_opts="-fault_overwrite -fault_good_run -fault_tw 20ns:940ns -fault_type set+1000ps -input strobe.tcl"


# run simulation
$bin_path/xmsim $xmsim_opts $fi_opts xil_defaultlib.Symbol_mapper_tb -input Symbol_mapper_tb_simulate.do
