#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 05 11:27:39 CEST 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Symbol_mapper_tb_func_synth -key {Post-Synthesis:sim_1:Functional:Symbol_mapper_tb} -tclbatch Symbol_mapper_tb.tcl -log simulate.log"
xsim Symbol_mapper_tb_func_synth -key {Post-Synthesis:sim_1:Functional:Symbol_mapper_tb} -tclbatch Symbol_mapper_tb.tcl -log simulate.log

