# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "fifo_generator_0_synth_1" START { ROLLUP_AUTO }
set_param simulator.xceliumInstallPath /ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin
set_msg_config  -id {BD 41-759}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMODT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMPARITY' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMRAMRSTN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_ERROROUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_ERRORSTATUS' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_INITB' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_JTAGTCK' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_JTAGTDI' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_JTAGTDO' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_JTAGTMS' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MIO' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_PORB' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_PROGB' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_RCALIBINOUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_SRSTB' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_ZQ' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXN0IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXN1IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXN2IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXN3IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXP0IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXP1IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXP2IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTRXP3IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_PADI' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFN0IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFN1IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFN2IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFN3IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFP0IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFP1IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFP2IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_REFP3IN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -suppress 
set_msg_config  -id {Synth 8-7023}  -string {{WARNING: [Synth 8-7023] instance 'PS8_i' of module 'PS8' has 1015 connections declared, but only 957 given [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/vio_decoder' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_100_to_400bit/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_50_to_400bit/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/eth_tx_fifo_inst1/fifo1' at clock pin 'rd_clk' is different from the actual clock period '6.206', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/infomem_fifo/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/input_fifo_for_decoder0/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/input_fifo_for_decoder1/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/input_fifo_for_decoder2/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/input_fifo_for_decoder3/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst0/ldpc_decoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst0/sync_mem_inst/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst1/ldpc_decoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst1/sync_mem_inst/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst2/ldpc_decoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst2/sync_mem_inst/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst3/ldpc_decoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst3/sync_mem_inst/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/vio_encoder' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/LDPC_encoder_4x16_with_fsm_inst/LDPC_encoder_1x16_inst0/ldcp_encoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/LDPC_encoder_4x16_with_fsm_inst/LDPC_encoder_1x16_inst1/ldcp_encoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/LDPC_encoder_4x16_with_fsm_inst/LDPC_encoder_1x16_inst2/ldcp_encoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '5.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/LDPC_encoder_4x16_with_fsm_inst/LDPC_encoder_1x16_inst3/ldcp_encoder' at clock pin 'm_axis_dout_aclk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/LDPC_encoder_4x16_with_fsm_inst/infomem_fifo/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/LDPC_encoder_4x16_with_fsm_inst/input_fifo_encoder/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/bit_vect_64_to_BB_symbol_conv_inst/converter_to_16bit/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/bit_vect_64_to_BB_symbol_conv_inst/converter_to_32bit/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/bit_vect_64_to_BB_symbol_conv_inst/converter_to_8bit/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/eth_rx_fifo_dual_clk_inst0/fifo1' at clock pin 'rd_clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'encoder_subsystem_inst/fifo_wrap_single_clk_large2_inst/fifo1' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'vio_top_file' at clock pin 'clk' is different from the actual clock period '4.545', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Vivado 12-1790}  -string {{CRITICAL WARNING: [Vivado 12-1790] Evaluation License Warning: This design contains one or more IP cores that use separately licensed features. If the design has been configured to make use of evaluation features, please note that these features will cease to function after a certain period of time. Please consult the core datasheet to determine whether the core which you have configured will be affected. Evaluation features should NOT be used in production systems.

Evaluation cores found in this design:
    IP core 'xxv_ethernet_0' (xxv_ethernet_v4_0_0) was generated with multiple features:
        IP feature 'x_eth_mac@2021.06' was enabled using a design_linking license.
        IP feature 'xxv_eth_basekr@2021.06' was enabled using a design_linking license.
        IP feature 'xxv_eth_mac_pcs@2021.06' was enabled using a design_linking license.
        IP feature 'xxv_tsn_802d1cm@2021.06' was enabled using a design_linking license.

Resolution: If a new IP Core license was added, in order for the new license to be picked up, the current netlist needs to be updated by resetting and re-generating the IP output products before bitstream generation.}}  -suppress 
set_msg_config  -id {XPM_CDC_GRAY: TCL-1000}  -string {{WARNING: [XPM_CDC_GRAY: TCL-1000] The source and destination clocks are the same. 
     Instance: decoder_subsystem_inst/ldpc_decoder_4x16_with_fsm_inst/ldpc_decoder_1x16_inst0/ldpc_decoder/inst/STD_5G_G.STD_5G_I/SDFEC_5G_IP.CDC_I/STATUS_IF_SYNC_I/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst 
  This will add unnecessary latency to the design. Please check the design for the following: 
 1) Manually instantiated XPM_CDC modules: Xilinx recommends that you remove these modules. 
 2) Xilinx IP that contains XPM_CDC modules: Verify the connections to the IP to determine whether you can safely ignore this message.
 [C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl:16]}}  -suppress 
set_msg_config  -id {XPM_CDC_GRAY: TCL-1000}  -suppress 
set_msg_config  -id {Synth 8-3295}  -suppress 
set_msg_config  -id {Timing 38-127}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-627}  -string {{WARNING: [Vivado 12-627] No clocks matched 'clk_out3_clk_wiz_0'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:4]}}  -suppress 
set_msg_config  -id {Vivado 12-627}  -string {{WARNING: [Vivado 12-627] No clocks matched 'txoutclk_out[0]_1'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:4]}}  -suppress 
set_msg_config  -id {Vivado 12-627}  -string {{WARNING: [Vivado 12-627] No clocks matched 'clk_out3_clk_wiz_0'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:5]}}  -suppress 
set_msg_config  -id {Vivado 12-627}  -string {{WARNING: [Vivado 12-627] No clocks matched 'rxoutclk_out[0]_1'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:6]}}  -suppress 
set_msg_config  -id {Vivado 12-627}  -string {{WARNING: [Vivado 12-627] No clocks matched 'rxoutclk_out[0]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:7]}}  -suppress 
set_msg_config  -id {Vivado 12-627}  -string {{WARNING: [Vivado 12-627] No clocks matched 'txoutclk_out[0]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:8]}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks {txoutclk_out[0]_1}]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:4]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group '. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:4]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks clk_out3_clk_wiz_0]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:5]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group '. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:5]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks {rxoutclk_out[0]_1}]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:6]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group '. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:6]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks {rxoutclk_out[0]}]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:7]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group '. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:7]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks {txoutclk_out[0]}]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:8]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group '. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:8]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks clk_out3_clk_wiz_0]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:4]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Project 1-498}  -string {{WARNING: [Project 1-498] One or more constraints failed evaluation while reading constraint file [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc] and the design contains unresolved black boxes. These constraints will be read post-synthesis (as long as their source constraint file is marked as used_in_implementation) and should be applied correctly then. You should review the constraints listed in the file [.Xil/ldpc_enc_dec_fpga_propImpl.xdc] and check the run log file to verify that these constraints were correctly applied.}}  -suppress 
set_msg_config  -id {Power 33-332}  -string {{WARNING: [Power 33-332] Found switching activity that implies high-fanout reset nets being asserted for excessive periods of time which may result in inaccurate power analysis.
Resolution: To review and fix problems, please run Power Constraints Advisor in the GUI from Tools > Power Constraints Advisor or run report_power with the -advisory option to generate a text report.}}  -suppress 
set_msg_config  -id {Timing 38-436}  -string {{WARNING: [Timing 38-436] There are set_bus_skew constraint(s) in this design. Please run report_bus_skew to ensure that bus skew requirements are met.}}  -suppress 
set_msg_config  -id {DRC PDCN-1569}  -string {{WARNING: [DRC PDCN-1569] LUT equation term check: Used physical LUT pin 'A3' of cell dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/temp_curid[31]_i_1 (pin dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/temp_curid[31]_i_1/I0) is not included in the LUT equation: 'O5=(A5*A1)+(A5*(~A1)*(~A2))+((~A5))'. If this cell is a user instantiated LUT in the design, please remove connectivity to the pin or change the equation and/or INIT string of the LUT to prevent this issue. If the cell is inferred or IP created LUT, please regenerate the IP and/or resynthesize the design to attempt to correct the issue.}}  -suppress 
set_msg_config  -id {DRC PDCN-1569}  -string {{WARNING: [DRC PDCN-1569] LUT equation term check: Used physical LUT pin 'A4' of cell dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/temp_curid[31]_i_1 (pin dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/temp_curid[31]_i_1/I1) is not included in the LUT equation: 'O5=(A5*A1)+(A5*(~A1)*(~A2))+((~A5))'. If this cell is a user instantiated LUT in the design, please remove connectivity to the pin or change the equation and/or INIT string of the LUT to prevent this issue. If the cell is inferred or IP created LUT, please regenerate the IP and/or resynthesize the design to attempt to correct the issue.}}  -suppress 
set_msg_config  -id {DRC PDCN-1569}  -string {{WARNING: [DRC PDCN-1569] LUT equation term check: Used physical LUT pin 'A5' of cell dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.id_state[0]_i_1 (pin dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.id_state[0]_i_1/I0) is not included in the LUT equation: 'O6=(A6+~A6)*((A1))'. If this cell is a user instantiated LUT in the design, please remove connectivity to the pin or change the equation and/or INIT string of the LUT to prevent this issue. If the cell is inferred or IP created LUT, please regenerate the IP and/or resynthesize the design to attempt to correct the issue.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC_SP.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[1].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC_SP.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[2].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC_SP.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (encoder_subsystem_inst/bit_vect_64_to_BB_symbol_conv_inst/converter_to_32bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[3].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC_SP.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {BD 41-759}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[4].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC_SP.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (decoder_subsystem_inst/LLR_BB_symbol_to_LDPC_decoder_converter_inst0/converter_200_to_400bit/fifo1/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[5].ram.r/prim_noinit.ram/DEVICE_8SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC_SP.ram) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {DRC RTSTAT-10}  -string {{WARNING: [DRC RTSTAT-10] No routable loads: 256 net(s) have no routable loads. The problem bus(es) and/or net(s) are dbg_hub/inst/BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gr1.gr1_int.rfwft/aempty_fwft_i, dbg_hub/inst/BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_CTL/ctl_reg[2:0], dbg_hub/inst/BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_CTL/ctl_reg_en_2[1], dbg_hub/inst/BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD1/ctl_reg_en_2[1], dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/m_bscan_capture[0], dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/m_bscan_drck[0], dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_switch/m_bscan_runtest[0], dbg_hub/inst/BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_WR/U_WR_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwhf.whf/overflow, dbg_hub/inst/BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwhf.whf/overflow, encoder_subsystem_inst/vio_encoder/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/probe_out0[15:0], decoder_subsystem_inst/vio_decoder/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/probe_out0[15:0], vio_top_file/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/probe_out0[8], vio_top_file/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/probe_out0[9], vio_top_file/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/probe_out0[10], vio_top_file/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/probe_out0[11]... and (the first 15 of 96 listed).}}  -suppress 
set_msg_config  -id {DRC PDCN-1569}  -suppress 
set_msg_config  -id {DRC RTSTAT-10}  -suppress 
set_msg_config  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks clk_out3_clk_wiz_0]'. [C:/5_SC_baseband/SD_FEC_5G_complete/src/CONSTR_XDC/LL_pins.xdc:9]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v4_0_0_cl73autoneg_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:186731]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v4_0_0_cl73autoneg_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:186753]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v4_0_0_cl73autoneg_10G_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:190540]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v4_0_0_32b_cl73autoneg_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:224803]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v4_0_0_32b_cl73autoneg_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:224823]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v1_0_xilinx_cl73autoneg_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:278925]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v1_0_xilinx_cl73autoneg_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:278936]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -new_severity {ERROR} 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in xxv_ethernet_v4_0_0_cl73autoneg_10G_an_pcontrol with formal parameter declaration list [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/hdl/xxv_ethernet_v4_0_vl_rfs.sv:190562]}}  -suppress 
set_msg_config  -id {Constraints 18-619}  -string {{WARNING: [Constraints 18-619] A clock with name 'gt_refclk_p[0]' already exists, overwriting the previous clock with the same name. [c:/5_SC_baseband/sd_fec_5g_compl.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0.xdc:65]}}  -suppress 
set_msg_config  -id {Timing 38-277}  -string {{WARNING: [Timing 38-277] The instance 'inst/i_xxv_ethernet_0_gt/inst/gen_gtwizard_gtye4_top.xxv_ethernet_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST' has RXOUTCLKSEL pins that are not constant, so the corresponding mux will select the input(s) having the worst case (highest frequency) clock(s) for automatic derivation of generated clocks}}  -suppress 
set_msg_config  -id {Synth 8-565}  -string {{WARNING: [Synth 8-565] redefining clock 'gt_refclk_p[0]'}}  -suppress 
set_msg_config  -id {Timing 38-277}  -string {{WARNING: [Timing 38-277] The instance 'inst/i_xxv_ethernet_0_gt/inst/gen_gtwizard_gtye4_top.xxv_ethernet_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST' has TXOUTCLKSEL pins that are not constant, so the corresponding mux will select the input(s) having the worst case (highest frequency) clock(s) for automatic derivation of generated clocks}}  -suppress 
set_msg_config  -id {Timing 38-277}  -string {{WARNING: [Timing 38-277] The instance 'inst/i_xxv_ethernet_0_gt_1/inst/gen_gtwizard_gtye4_top.xxv_ethernet_0_gt_1_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST' has RXOUTCLKSEL pins that are not constant, so the corresponding mux will select the input(s) having the worst case (highest frequency) clock(s) for automatic derivation of generated clocks}}  -suppress 
set_msg_config  -id {Timing 38-277}  -string {{WARNING: [Timing 38-277] The instance 'inst/i_xxv_ethernet_0_gt_1/inst/gen_gtwizard_gtye4_top.xxv_ethernet_0_gt_1_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST' has TXOUTCLKSEL pins that are not constant, so the corresponding mux will select the input(s) having the worst case (highest frequency) clock(s) for automatic derivation of generated clocks}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[35] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[34] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[33] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[32] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[31] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[30] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[29] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[28] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[27] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[26] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[25] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[24] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[23] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[22] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[21] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[20] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[19] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[18] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[17] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[16] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[15] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[14] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[13] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[12] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[11] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[10] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[9] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[8] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[7] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[6] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[5] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[4] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[3] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[2] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[1] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[0] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3295}  -string {{WARNING: [Synth 8-3295] tying undriven pin inst:sl_iport0[36] to constant 0}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXN1OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXN2OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXN3OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXP0OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXP1OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXP2OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_MGTTXP3OUT' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_PADO' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_BOOTMODE' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_CLK' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DONEB' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMA' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMACTN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMALERTN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMBA' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMBG' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMCK' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMCKE' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMCKN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMCSN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMDM' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMDQ' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMDQS' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'PSS_ALTO_CORE_PAD_DRAMDQSN' of module 'PS8' is unconnected for instance 'PS8_i' [c:/sd_fec_5g_compl.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/hdl/zynq_ultra_ps_e_v3_3_5.v:3882]}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu28dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/miglioranza/FEC/FEC.cache/wt [current_project]
set_property parent.project_path /home/miglioranza/FEC/FEC.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu111:part0:1.4 [current_project]
set_property ip_repo_paths /home/miglioranza/FEC/FEC.srcs [current_project]
update_ip_catalog
set_property ip_output_repo /home/miglioranza/FEC/FEC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet /home/miglioranza/FEC/FEC.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1 -new_name fifo_generator_0 -ip [get_ips fifo_generator_0]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fifo_generator_0 -part xczu28dr-ffvg1517-2-e -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix fifo_generator_0_ fifo_generator_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_0_stub.v
 lappend ipCachedFiles fifo_generator_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_0_stub.vhdl
 lappend ipCachedFiles fifo_generator_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_0_sim_netlist.v
 lappend ipCachedFiles fifo_generator_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_0_sim_netlist.vhdl
 lappend ipCachedFiles fifo_generator_0_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp fifo_generator_0.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips fifo_generator_0]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all fifo_generator_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fifo_generator_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "fifo_generator_0_synth_1_synth_report_utilization_0" "report_utilization -file fifo_generator_0_utilization_synth.rpt -pb fifo_generator_0_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.v /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.vhdl /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.v /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/miglioranza/FEC/FEC.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.vhdl /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cacheID 

if {[file isdir /home/miglioranza/FEC/FEC.ip_user_files/ip/fifo_generator_0]} {
  catch { 
    file copy -force /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.v /home/miglioranza/FEC/FEC.ip_user_files/ip/fifo_generator_0
  }
}

if {[file isdir /home/miglioranza/FEC/FEC.ip_user_files/ip/fifo_generator_0]} {
  catch { 
    file copy -force /home/miglioranza/FEC/FEC.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_stub.vhdl /home/miglioranza/FEC/FEC.ip_user_files/ip/fifo_generator_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "fifo_generator_0_synth_1" END { }
