# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/miglioranza/Control_unit_transmitter/Control_unit_transmitter.srcs/sources_1/ip/tx_data_fifo/tx_data_fifo.xci
# IP: The module: 'tx_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miglioranza/Control_unit_transmitter/Control_unit_transmitter.gen/sources_1/ip/tx_data_fifo/tx_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/miglioranza/Control_unit_transmitter/Control_unit_transmitter.srcs/sources_1/ip/tx_data_fifo/tx_data_fifo.xci
# IP: The module: 'tx_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miglioranza/Control_unit_transmitter/Control_unit_transmitter.gen/sources_1/ip/tx_data_fifo/tx_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
