# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Polyphase_filter.xdc

# IP: ip/axis_data_fifo_poly_filter/axis_data_fifo_poly_filter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_poly_filter || ORIG_REF_NAME==axis_data_fifo_poly_filter} -quiet] -quiet
