create_clock -name clk -period 5 [get_ports clk]
set_false_path -from [get_ports {data_in[*]}]
set_false_path -to   [get_ports {data_out0[*]}]
set_false_path -to   [get_ports {data_out1[*]}]
set_false_path -to   [get_ports {data_out2[*]}]
set_false_path -to   [get_ports {data_out3[*]}]
set_false_path -to   [get_ports {data_out_valid[*]}]
set_false_path -from [get_ports {reset}]
set_false_path -from [get_ports {reset_fifos}] 
set_false_path -from [get_ports {end_of_frame}] 
set_false_path -from [get_ports {data_in_ready}] 
set_false_path -from [get_ports {data_in_valid}] 
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data0_reg[14]/C] -to [get_pins LDPC_core0/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[14]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data1_reg[14]/C] -to [get_pins LDPC_core1/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[14]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data2_reg[14]/C] -to [get_pins LDPC_core2/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[14]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data3_reg[14]/C] -to [get_pins LDPC_core3/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[14]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data0_reg[11]/C] -to [get_pins LDPC_core0/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[11]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data1_reg[11]/C] -to [get_pins LDPC_core1/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[11]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data2_reg[11]/C] -to [get_pins LDPC_core2/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[11]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data3_reg[11]/C] -to [get_pins LDPC_core3/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[11]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data0_reg[15]/C] -to [get_pins LDPC_core0/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[15]]
#set_min_delay  0.5 -from [get_pins Data_controller_inst/dout_data1_reg[15]/C] -to [get_pins LDPC_core1/inst/STD_OTHER_G.STD_OTHER_I/FE_I/S_AXIS_DIN_TDATA[15]]