#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 24 12:10:51 CEST 2024
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# installation path setting
bin_path="/ihp/ihpusr/cadence/xcelium/20.09/tools.lnx86/bin"

# set xmsim command line args
xmsim_opts=" -64bit -logfile simulate.log -gui"

#set fault injection parameters
fi_opts="-fault_overwrite -fault_good_run -fault_type seu -fault_tw 200ns:250ns  -input strobe.tcl"

# run simulation
$bin_path/xmsim $xmsim_opts $fi_opts xil_defaultlib.Polyphase_filter_tb -input Polyphase_filter_tb_simulate.do
